### ISSUE TITLE
Replace deprecated typing.re with typing

### ISSUE THREAD

**Issue by nifadyev** [wemake-services/dotenv-linter#710]
# Bug report

## What's wrong

`typing.re` is deprecated and will be removed in python 3.13

```bash
dotenv_linter/visitors/fst/names.py:3
  /dotenv-linter/dotenv_linter/visitors/fst/names.py:3: DeprecationWarning: typing.re is deprecated, import directly from typing instead. typing.re will be removed in Python 3.13.
    from typing.re import Pattern
```

## How is that should be

Use `from typing import Pattern` instead

**Comment by winter0mute** [comment]
Just hit this when I tried to use `dotenv-linter` in `pre-commit`:
```
dotenv-linter................................................................Failed
- hook id: dotenv-linter
- exit code: 1

Traceback (most recent call last):
  File "/Users/myuser/.cache/pre-commit/repom_ojbvli/py_env-python3.13/bin/dotenv-linter", line 5, in <module>
    from dotenv_linter.cli import cli
  File "/Users/myuser/.cache/pre-commit/repom_ojbvli/py_env-python3.13/lib/python3.13/site-packages/dotenv_linter/cli.py", line 11, in <module>
    from dotenv_linter.checker import DotenvFileChecker
  File "/Users/myuser/.cache/pre-commit/repom_ojbvli/py_env-python3.13/lib/python3.13/site-packages/dotenv_linter/checker.py", line 12, in <module>
    from dotenv_linter.visitors.fst import assigns, comments, names, values
  File "/Users/myuser/.cache/pre-commit/repom_ojbvli/py_env-python3.13/lib/python3.13/site-packages/dotenv_linter/visitors/fst/names.py", line 3, in <module>
    from typing.re import Pattern
ModuleNotFoundError: No module named 'typing.re'; 'typing' is not a package
```

**Comment by jozsefgaugesz** [comment]
Just checked the [dotenv_linter/visitors/fst/names.py](https://github.com/wemake-services/dotenv-linter/blob/75b3fefa0d8904ced50b431f4dc6f6451f485ec9/dotenv_linter/visitors/fst/names.py) and looks like the issue was fixed in commit https://github.com/wemake-services/dotenv-linter/commit/75b3fefa0d8904ced50b431f4dc6f6451f485ec9 but there was no new release since then.

Can we have a new release, please? :wink:
Thanks!

**Comment by sobolevn** [comment]
Done, 0.6.0 released!
